"""initial session table

Revision ID: dbe622ee26fb
Revises: 
Create Date: 2026-02-19 05:12:48.485343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe622ee26fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('representation', sa.String(length=50), nullable=True),
    sa.Column('approach', sa.String(length=50), nullable=True),
    sa.Column('aggressiveness', sa.Integer(), nullable=True),
    sa.Column('target_filename', sa.String(length=255), nullable=True),
    sa.Column('target_path', sa.Text(), nullable=True),
    sa.Column('parsed_doc_path', sa.Text(), nullable=True),
    sa.Column('precedent_path', sa.Text(), nullable=True),
    sa.Column('revisions_count', sa.Integer(), nullable=False),
    sa.Column('flags_count', sa.Integer(), nullable=False),
    sa.Column('is_test_session', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
